<?php

namespace ContainerEBCg59S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LmmqHlyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LmmqHly' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LmmqHly'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\QuestionsController::addAnswer' => ['privates', '.service_locator.BGzrS37', 'get_ServiceLocator_BGzrS37Service', true],
            'App\\Controller\\QuestionsController::addQuestion' => ['privates', '.service_locator.BGzrS37', 'get_ServiceLocator_BGzrS37Service', true],
            'App\\Controller\\QuestionsController::deleteAnswer' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\QuestionsController::deleteQuestion' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\QuestionsController::editAnswer' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\QuestionsController::editQuestion' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\QuestionsController::index' => ['privates', '.service_locator.cdXRdN3', 'get_ServiceLocator_CdXRdN3Service', true],
            'App\\Controller\\QuestionsController::showAnswers' => ['privates', '.service_locator.OW.dyDV', 'get_ServiceLocator_OW_DyDVService', true],
            'App\\Controller\\QuizsController::delete' => ['privates', '.service_locator.vbJ7INo', 'get_ServiceLocator_VbJ7INoService', true],
            'App\\Controller\\QuizsController::edit' => ['privates', '.service_locator.vbJ7INo', 'get_ServiceLocator_VbJ7INoService', true],
            'App\\Controller\\QuizsController::new' => ['privates', '.service_locator.UcyCjMw', 'get_ServiceLocator_UcyCjMwService', true],
            'App\\Controller\\QuizsController::open' => ['privates', '.service_locator.Zaxiz_K', 'get_ServiceLocator_ZaxizKService', true],
            'App\\Controller\\QuizsController::pdf' => ['privates', '.service_locator.vbJ7INo', 'get_ServiceLocator_VbJ7INoService', true],
            'App\\Controller\\QuizsController::stats' => ['privates', '.service_locator.kMzjVaf', 'get_ServiceLocator_KMzjVafService', true],
            'App\\Controller\\QuizsController::view' => ['privates', '.service_locator.kMzjVaf', 'get_ServiceLocator_KMzjVafService', true],
            'App\\Controller\\QuizsController::view2' => ['privates', '.service_locator.kMzjVaf', 'get_ServiceLocator_KMzjVafService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\QuestionsController:addAnswer' => ['privates', '.service_locator.BGzrS37', 'get_ServiceLocator_BGzrS37Service', true],
            'App\\Controller\\QuestionsController:addQuestion' => ['privates', '.service_locator.BGzrS37', 'get_ServiceLocator_BGzrS37Service', true],
            'App\\Controller\\QuestionsController:deleteAnswer' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\QuestionsController:deleteQuestion' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\QuestionsController:editAnswer' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\QuestionsController:editQuestion' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\QuestionsController:index' => ['privates', '.service_locator.cdXRdN3', 'get_ServiceLocator_CdXRdN3Service', true],
            'App\\Controller\\QuestionsController:showAnswers' => ['privates', '.service_locator.OW.dyDV', 'get_ServiceLocator_OW_DyDVService', true],
            'App\\Controller\\QuizsController:delete' => ['privates', '.service_locator.vbJ7INo', 'get_ServiceLocator_VbJ7INoService', true],
            'App\\Controller\\QuizsController:edit' => ['privates', '.service_locator.vbJ7INo', 'get_ServiceLocator_VbJ7INoService', true],
            'App\\Controller\\QuizsController:new' => ['privates', '.service_locator.UcyCjMw', 'get_ServiceLocator_UcyCjMwService', true],
            'App\\Controller\\QuizsController:open' => ['privates', '.service_locator.Zaxiz_K', 'get_ServiceLocator_ZaxizKService', true],
            'App\\Controller\\QuizsController:pdf' => ['privates', '.service_locator.vbJ7INo', 'get_ServiceLocator_VbJ7INoService', true],
            'App\\Controller\\QuizsController:stats' => ['privates', '.service_locator.kMzjVaf', 'get_ServiceLocator_KMzjVafService', true],
            'App\\Controller\\QuizsController:view' => ['privates', '.service_locator.kMzjVaf', 'get_ServiceLocator_KMzjVafService', true],
            'App\\Controller\\QuizsController:view2' => ['privates', '.service_locator.kMzjVaf', 'get_ServiceLocator_KMzjVafService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\QuestionsController::addAnswer' => '?',
            'App\\Controller\\QuestionsController::addQuestion' => '?',
            'App\\Controller\\QuestionsController::deleteAnswer' => '?',
            'App\\Controller\\QuestionsController::deleteQuestion' => '?',
            'App\\Controller\\QuestionsController::editAnswer' => '?',
            'App\\Controller\\QuestionsController::editQuestion' => '?',
            'App\\Controller\\QuestionsController::index' => '?',
            'App\\Controller\\QuestionsController::showAnswers' => '?',
            'App\\Controller\\QuizsController::delete' => '?',
            'App\\Controller\\QuizsController::edit' => '?',
            'App\\Controller\\QuizsController::new' => '?',
            'App\\Controller\\QuizsController::open' => '?',
            'App\\Controller\\QuizsController::pdf' => '?',
            'App\\Controller\\QuizsController::stats' => '?',
            'App\\Controller\\QuizsController::view' => '?',
            'App\\Controller\\QuizsController::view2' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\QuestionsController:addAnswer' => '?',
            'App\\Controller\\QuestionsController:addQuestion' => '?',
            'App\\Controller\\QuestionsController:deleteAnswer' => '?',
            'App\\Controller\\QuestionsController:deleteQuestion' => '?',
            'App\\Controller\\QuestionsController:editAnswer' => '?',
            'App\\Controller\\QuestionsController:editQuestion' => '?',
            'App\\Controller\\QuestionsController:index' => '?',
            'App\\Controller\\QuestionsController:showAnswers' => '?',
            'App\\Controller\\QuizsController:delete' => '?',
            'App\\Controller\\QuizsController:edit' => '?',
            'App\\Controller\\QuizsController:new' => '?',
            'App\\Controller\\QuizsController:open' => '?',
            'App\\Controller\\QuizsController:pdf' => '?',
            'App\\Controller\\QuizsController:stats' => '?',
            'App\\Controller\\QuizsController:view' => '?',
            'App\\Controller\\QuizsController:view2' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
