<?php

namespace ContainerEBCg59S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZaxizKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zaxiz_K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zaxiz_K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'questionsRepository' => ['privates', 'App\\Repository\\QuestionsRepository', 'getQuestionsRepositoryService', true],
            'quiz' => ['privates', '.errored..service_locator.Zaxiz_K.App\\Entity\\Quizs', NULL, 'Cannot autowire service ".service_locator.Zaxiz_K": it references class "App\\Entity\\Quizs" but no such service exists.'],
        ], [
            'questionsRepository' => 'App\\Repository\\QuestionsRepository',
            'quiz' => 'App\\Entity\\Quizs',
        ]);
    }
}
