<?php

namespace ContainerEBCg59S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UcyCjMwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UcyCjMw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UcyCjMw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'flashy' => ['services', 'mercuryseries_flashy.flashy_notifier', 'getMercuryseriesFlashy_FlashyNotifierService', true],
            'quizsRepository' => ['privates', 'App\\Repository\\QuizsRepository', 'getQuizsRepositoryService', true],
        ], [
            'flashy' => '?',
            'quizsRepository' => 'App\\Repository\\QuizsRepository',
        ]);
    }
}
