<?php

namespace ContainerEBCg59S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Zaxiz_K.App\Entity\Quizs' shared service.
     *
     * @return \App\Entity\Quizs
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Zaxiz_K": it references class "App\\Entity\\Quizs" but no such service exists.');
    }
}
