<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEBCg59S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEBCg59S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEBCg59S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEBCg59S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEBCg59S\App_KernelDevDebugContainer([
    'container.build_hash' => 'EBCg59S',
    'container.build_id' => '5cf935bc',
    'container.build_time' => 1682758438,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEBCg59S');
